config/routes.rb
Rails.application.routes.draw do
  resources :items do
    get :upvote, on: :member
    get :expensive, on: :collection
  end
  root  'items#index'
  # get ':controller(/:action(/:id))(.:format)'
end

app/models/item.rb
class Item < ActiveRecord::Base
	validates :price, numericality: { greater_than: 0, allow_nil: true }
	validates :name, presence: true

	# after_initialize {puts 'initialized'} # Item.new; Item.first
	# after_save { puts 'save' } # Item.save; Item.create; item.update_attributes()
	# after_create { puts 'created' }
	# after_update { puts 'updated' }
	# after_destroy { puts 'destroyed' } # Item.destroy
end

app/controllers/application_controller.rb
#
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def render_403
    render file: 'public/403.html', status: 403
  end

  def render_404
    render file: 'public/404.html', status: 404
  end

  def check_if_admin
    # render_403 unless params[:admin]
    # render text: 'Access denied', status: 403 unless params[:admin]
  end
end

app/controllers/items_controller.rb
#
class ItemsController < ApplicationController
  before_filter :find_item, only: [:show, :edit, :update, :destroy, :upvote]
  before_filter :check_if_admin,
                 only: [:edit, :update,:new, :create, :destroy]

  def index
    @items = Item.all
    @expensive = false
  end

  def expensive
    @items = Item.where('price > 1000')
    @expensive = true
    render 'index'
  end
  # /items/1 GET
  def show
    unless @item
      render text: 'Page not found', status: 404
    end
  end
  # /items/new GET
  def new
    @item = Item.new
  end
  # /items/1/edit GET
  def edit
    # @item = Item.find(params[:id])
  end
  # /items POST
  def create
    item_params = params.require(:item).permit(:name, :price, :description,
                                               :weight, :real)
    @item = Item.create(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render 'new'
    end
  end
  # /items/1 PUT
  def update
    # @item = Item.find(params[:id])
    item_params = params.require(:item).permit(:name, :price, :description,
                                               :weight, :real)
    @item.update_attributes(item_params)
    if @item.errors.empty?
      redirect_to item_path(@item)
    else
      render 'edit'
    end
  end
  # /items/1 DELET
  def destroy
    # @item = Item.find(params[:id])
    @item.destroy
    # redirect_to action: 'index'
    redirect_to items_path
  end

  def upvote
    @item.increment!(:votes_count)
    # redirect_to action: :index
    redirect_to items_path
  end

  private

  def find_item
    @item = Item.where(id: params[:id]).first
    render_404 unless  @item
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/edit.html.erb
<h1>Edit item</h1>

<%= form_for @item do |f| %>

  <p>Цена: <br/><%= f.text_field :price %></p>
  <p>Название: <br/><%= f.text_field :name %></p>
  <p>Описание: <br/><%= f.text_field :description %></p>
  <p>Вес: <br/><%= f.text_field :weight %></p>

  <p><%= f.submit 'Сохранить товар' %></p>

<% end %>

app/views/items/index.html.erb
<h1>Items</h1>

<p><%= link_to 'Добавить товар', new_item_path %></p>

<% if @items.empty? %>
  <b>No items in store</b>
<% else %>
  <table>
    <tr>
      <th>item id</th>
      <th>Name</th>
      <th>Price</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>

    <% @items.each do |i| %>

      <tr>
        <td><%= i.id %></td>
        <td><%= link_to i.name, item_path(i) %></td>
        <td><%= i.price %> руб.</td>
        <td><%= link_to 'Удалить', item_path(i),
                method: :delete,
                data: { confirm: 'Вы уверены?' } %></td>
        <td><%= button_to 'Редактировать', edit_item_path(i),
                method: :get %></td>
        <td>Рейтинг: <%= i.votes_count %>, 
                     <%= link_to '+', upvote_item_path(i) %></td>
       </tr>

    <% end %>

  </table>
<% end %>

<% unless @expensive %>

  <h3><%= link_to 'Дорогие товары', expensive_items_path %></h3>

<% else %>

  <h3><%= link_to 'back', items_path %></h3>

<% end %>

app/views/items/new.html.erb
<h1>Create new item</h1>

<%= form_for @item do |f| %>

  <p>Цена: <br/><%= f.text_field :price %></p>
  <p>Название: <br/><%= f.text_field :name %></p>
  <p>Описание: <br/><%= f.text_field :description %></p>
  <p>Вес: <br/><%= f.text_field :weight %></p>

  <p><%= f.submit 'Создать товар' %></p>

<% end %>

app/views/items/show.html.erb
<h1><%= @item.name %></h1>

<ul>
  <li><%= @item.price %>руб.</li>
  <li><%= @item.description %></li>
  <li>Вес: <%= @item.weight %>кг.</li>

</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyStore</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>